apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-vue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-vue
  template:
    metadata:
      labels:
        app: go-vue
    spec:
      containers:
        - name: go-vue-container
          image: asia-east1-docker.pkg.dev/goandvue20260215/my-repo/go-vue-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "redis:6379"